import json
import logging
from typing import Any

from app.core import sqlite_client
from app.core.gemini import GeminiClient

logger = logging.getLogger("services.game_master")


class GameMasterService:
    """
    The Ultimate 'Zero-Fat' & 'Total Understanding' Service.
    Instead of relying on fragile web scraping or blocked APIs,
    this service uses Gemini's deep knowledge base to reconstruct
    a complete, beginner-ready guide from English primary sources.
    """

    def __init__(self):
        self.gemini = GeminiClient()

    async def generate_and_save_game_guide(self, game_name: str) -> dict[str, Any]:
        logger.info(f"Initiating High-Res Rule Reconstruction for: {game_name}")

        prompt = f"""
        あなたは世界一分かりやすいボードゲームのインストラクターです。
        ボードゲーム「{game_name}」の公式英語ルールブックの知識を元に、
        「全くルールを知らない日本人の初心者が、この情報を読むだけで今すぐ遊べる」レベルの
        完全な構造化ガイドを作成してください。

        【出力要件 (JSON形式のみ)】:
        {{
            "title": "ゲームの正式名称（日本語）",
            "title_en": "Game's official English name",
            "slug": "url-friendly-slug-name",
            "min_players": 最小プレイ人数(数値),
            "max_players": 最大プレイ人数(数値),
            "play_time": 平均プレイ時間(数値、分),
            "min_age": 対象年齢(数値),
            "rules_summary": "ゲームの魅力と概要を伝える3行の紹介文",
            "rules_content": {{
                "intro": "世界観やテーマの短い説明",
                "objective": "このゲームで勝つために何を目指すべきか",
                "setup": "1ステップずつ、何をどこに置くかの準備手順",
                "turn_flow": "自分の手番でできることの完全な説明（選択肢と制限）",
                "scoring": "得点が入るタイミングと計算方法の全て",
                "end_game": "終了条件と最終順位の決め方",
                "first_step_advice": "初心者が最初の1手で考えるべき戦略的アドバイス"
            }}
        }}
        """

        # Phase 1 & 2: Generate the High-Res Guide
        # Let it crash (CDD) if Gemini fails or returns invalid JSON
        generated_data = await self.gemini.generate_structured_json(prompt)

        # Prepare for Persistence
        db_data = {
            "slug": generated_data["slug"],
            "title": generated_data["title"],
            "title_ja": generated_data["title"],
            "title_en": generated_data["title_en"],
            "description": generated_data["rules_content"]["intro"],
            "summary": generated_data["rules_summary"],
            "rules_summary": generated_data["rules_summary"],
            "rules_content": json.dumps(generated_data["rules_content"], ensure_ascii=False),
            "min_players": generated_data["min_players"],
            "max_players": generated_data["max_players"],
            "play_time": generated_data["play_time"],
            "min_age": generated_data["min_age"],
            "metadata": {"source": "gemini_high_res_reconstruction"},
            "infographics": {},
            "structured_data": {},
        }

        # Phase 3: Save to SQLite
        logger.info(f"Saving fully reconstructed guide to DB for: {db_data['slug']}")
        result = sqlite_client.upsert_game(db_data)

        return result

    def export_as_markdown(self, game_data: dict[str, Any]) -> str:
        """
        Convert structured game data into a clean Markdown document
        optimized for NotebookLM to generate visual assets.
        """
        rules = json.loads(game_data["rules_content"])

        md = f"""# {game_data["title"]} (Official Guide)

## 🌟 Game Objective
{rules["objective"]}

## 🛠️ Setup Instructions
{rules["setup"]}

## 🔄 Turn Flow (Step-by-Step)
{rules["turn_flow"]}

## 🔢 Scoring Rules
{rules["scoring"]}

## 🏁 Game End & Final Scoring
{rules["end_game"]}

## 💡 Pro Strategy Advice
{rules["first_step_advice"]}

---
Generated by RuleScribe Games GameMaster Engine
"""
        return md
